### ISSUE TITLE
Plus d'un équipement  avec l'option pollen

### ISSUE THREAD

**Issue by Ethal** [lunarok/jeedom_vigilancemeteo#34]
Bonjour Cédric, 

Si l'on crée plus d'un équipement avec l'option pollen, si l'on clique pour faire défiler le carrousel c'est l'ensemble des widgets qui défile ,

je pense que le problème vient du script qui est dans le template du widget qui gère le carroussel,

une piste:  rajouter l'id de l'équipement dans 
` <div id="pollen_slides">` et `var container = $('#pollen_slides ul');` ?
 
Merci

Ps : test effectué en V2.4 et V3 , même soucis,

**Comment by lunarok** [comment]
fait avec les commit du jour

**Comment by Ethal** [comment]
Je viens d'installer le plugin avec les modifs ,
c'est ok pour moi,merci
