### ISSUE TITLE
Localisation Undefined

### ISSUE THREAD

**Issue by cfouetillou** [lunarok/jeedom_vigilancemeteo#42]
Bonjour,

J'utilise l'appli Vigilance Météo. 

Lorsque je localise la vigilance Pollens, l'appli affiche bien les informations de mon département.

Par contre pour la même localisation, le site vigilance de Météo France renvoie Undefined.

![capture](https://user-images.githubusercontent.com/35970626/35641962-f0de8314-06c1-11e8-8608-b9560089cf54.PNG)

Est-ce normal ?

Merci.

Cédric

**Comment by lunarok** [comment]
Merci de consulter le forum pour le support
Je vois pas pourquoi on parle de météo france pour le pollen, se référer à la doc est une bonne base

**Comment by cfouetillou** [comment]
C'est pour vous expliquer que la géolocalisation marche avec la vigilance Pollens mais pas avec la Vigilance Météo France. 
La preuve avec la capture d'écran Météo France qui mentionne UNDEFINED
D'avance merci.
