### ISSUE TITLE
Un seul risque pris en compte

### ISSUE THREAD

**Issue by mycev** [lunarok/jeedom_vigilancemeteo#43]
Bonjour,
Lorsqu'il y a plusieurs 'risques' contenu dans le ficheir XML météofrance, par exemple :
DV dep="76" coul="2"
  risque val="4" /
  risque val="5" /
/DV
le code contenu dans vigilancemeteo.class.php qui et parse le risque écrase systématique la variable $lrisque, générant un seul message sur le dashboard de jeedom. Dans mon cas, je ne voyait qu’inondation et pas neige :-(

PS : les '<' et les '>' ont été retirés pour ne pas empêcher l'affichage...

**Comment by lunarok** [comment]
Moi j'ai bien les multiples risques. Donc merci d'apporter du concret comme des logs. Pas de support sur github, uniquement le forum

**Comment by mycev** [comment]
Il ne s'agit pas ici d'un support mais d'une proposition de modification du code dont une analyse m'a permis de détecter un problème... Perso, je peux faire la modification pour moi sur mon jeedom mais l'idée  est de partager cela...
Les logs n'affichent rien de particuliers. De quels risques parles-tu ? Comme évoqué dans mon post sur le forum, il n'y qu'une seule partie du code qui écrase le risque, il y a donc la possibilité de voir plusieurs information en simultané mais a priori pas le risque...

  foreach($data->getElementsByTagName('risque') as $risque) {
        switch ($risque->getAttribute('valeur')) {
          case 1:
          $lrisque = "vent";
          break;
          case 2:
          $lrisque = "pluie-inondation";
          break;
          case 3:
          $lrisque = "orages";
          break;
          case 4:
          $lrisque = "inondations";
          break;
          case 5:
          $lrisque = "neige-verglas";
          break;
          case 6:
          $lrisque = "canicule";
          break;
          case 7:
          $lrisque = "grand-froid";
          break;
        }
      }

Qu'il conviendrait de remplacer par :
  foreach($data->getElementsByTagName('risque') as $risque) {
        switch ($risque->getAttribute('valeur')) {
          case 1:
              if ($lrisque == "RAS") {
                $lrisque = "vent ";
              } else {
                $lrisque = $lrisque . ", vent ";
              }
          break;
    etc...

Le problème sera ensuite le codage de la couleur mais, on y peut rien, le xml de météofrance ne spécifie pas une couleur par risque mais une couleur pour l'ensemble des risques...

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_vigilancemeteo/commit/8ad032ad5c841c81e357fe646e5f1d137bce2ac6
