### ISSUE TITLE
Ajouter un paramètre max_retry sur les requêtes vers WAQI

### ISSUE THREAD

**Issue by micromad** [lunarok/jeedom_vigilancemeteo#44]
Salut Lunarok,

tout d'abord merci pour tes plugins qui sont juste excellents pour Jeedom.
Je t'écris car j'utilise ton plugin vigilancemeteo pour la qualité de l'air et j'ai régulièrement des erreurs dans Jeedom car la requête ne renvoie rien.
Il semble que le problème vienne de l'API WAQI qui ne répond pas une fois sur deux (j'ai fait des tests à la main). Pourrais-tu STP implémenter la possibilité de faire plusieurs requête (un paramètre max_retry) avant de considérer que la requête a échoué ?

J'ai vu qu'il est facilement possible de le faire avec le module curl de PHP.

Merci d'avance.
@+

**Comment by lunarok** [comment]
Il y a déjà 3 retries, il faut utiliser le refresh en cas de soucis à une heure non fixe

**Comment by micromad** [comment]
Il est où le bouton refresh sur le module qualite de l'air ?
