### ISSUE TITLE
Mises à jour des templates mobile et dashboard VigilanceMeteo et PrevisionPluie

### ISSUE THREAD

**Issue by Caelion** [lunarok/jeedom_vigilancemeteo#60]
Bonjour,
Je te propose une mise à jour des templates mobile et dashboard VigilanceMeteo et PrevisionPluie.
Les modifications consistent aux non forçages de la taille de police et suppression des lignes vides pour un affichage commun avec les templates de base Jeedom.
Je suis à ta disposition pour en discuter.
Caelion

[dashboard_previsionpluie.html.txt](https://github.com/lunarok/jeedom_vigilancemeteo/files/4176247/dashboard_previsionpluie.html.txt)
[dashboard_vigilancemeteo.html.txt](https://github.com/lunarok/jeedom_vigilancemeteo/files/4176248/dashboard_vigilancemeteo.html.txt)
[mobile_previsionpluie.html.txt](https://github.com/lunarok/jeedom_vigilancemeteo/files/4176338/mobile_previsionpluie.html.txt)
[mobile_vigilancemeteo.html.txt](https://github.com/lunarok/jeedom_vigilancemeteo/files/4176339/mobile_vigilancemeteo.html.txt)

**Comment by lunarok** [comment]
Les fichiers ne correspondent pas à la version actuelle des widgets
Il faut passer par un PR qu ece soit lisible les changements proposés

**Comment by Caelion** [comment]
Ok, je vais repartir de la mise à jour du plugin du 7/02 et faire le PR

**Comment by Caelion** [comment]
J'ai fait le PR.
Dis moi si tu es ok.
Bien à toi
