### ISSUE TITLE
Plugin affiche les données des crues dans la mauvaise unité

### ISSUE THREAD

**Issue by smoreau** [lunarok/jeedom_vigilancemeteo#64]
J'ai configuré le plugin pour les données de vigicrues de la manière suivante :
![Capture2](https://user-images.githubusercontent.com/1629624/79364001-fb608100-7f48-11ea-8a29-f42f108e2ac1.JPG)

Et voici ce que j'obtiens dans le dashboard :
![Capture](https://user-images.githubusercontent.com/1629624/79363998-f996bd80-7f48-11ea-8a6e-496665deab71.JPG)

La valeur devrait être soit 0,55m, soit 558mm.

**Comment by lunarok** [comment]
Ca dépend des sondes. Si elle est pas en mètres, il faut diviser par 1000
son résultat dans les options avancées de la commande.

Le mer. 15 avr. 2020 à 18:45, Stéphane Moreau <notifications@github.com> a
écrit :

**Comment by smoreau** [comment]
En effet, j'avais pensé à diviser par 1000, mais je me demandais si cela ne pouvait pas être détecté et corrigé directement dans le plugin.
J'ai configuré la division de mon côté en attendant votre retour. :)

**Comment by lunarok** [comment]
En fait le seul moyen serait de dire "si je vois un nombre à 4 chiffres,
c'est du mm" mais c'est super dangereux, car y a des cas ou ca va passer à
travers
Et malheureusement, la sonde de vigicrue ne dit pas son unité, ce qui
serait le top

Le ven. 17 avr. 2020 à 10:14, Stéphane Moreau <notifications@github.com> a
écrit :

**Comment by smoreau** [comment]
Oui, je comprends. En effet, ce serait trop dangereux.
Ou sinon, il faudrait ajouter une liste déroulante "Unité de la sonde" sur la page de configuration ?

**Comment by jim005** [comment]
Même constat que @smoreau  (sans avoir lu cette Issue oups...) je viens de pousser un [PR](https://github.com/lunarok/jeedom_vigilancemeteo/pull/70). Le PR contient d'autres mini suggestions.
Je laisse alors ma config aussi /1000 . Merci pour ce plugin

**Comment by jim005** [comment]
L'unité des données semble homogène via le nouveau format JSON. En XML, effectivement ça patine sur les unités. 

**Hauteur :** 
- XML : https://www.vigicrues.gouv.fr/services/observations.xml/?CdStationHydro=X045401001
- JSON : https://www.vigicrues.gouv.fr/services/observations.json/?CdStationHydro=X045401001

**Débit :** 
- XML : https://www.vigicrues.gouv.fr/services/observations.xml/?CdStationHydro=X045401001&GrdSerie=Q
- JSON : https://www.vigicrues.gouv.fr/services/observations.json/?CdStationHydro=X045401001&GrdSerie=Q

Attention en JSON, la date est en timestamp, pour l'avoir en ISO, ajout le pamêtre GET suivant : &FormatDate=iso . Suggestion bonus : tu pourrais affiner la date de collect pour prendre directement la source de la sonde via : `$cmd->setCache('collectDate', date('Y-m-d H:i:s'));`

voilà, dis moi si tu veux un PR sur ça. Je n'ai pas la vision complète du plugin, mais je peux te suggérer quelques points sur les sondes que j'ai dans mon Jeedom. ;-)

**Comment by lunarok** [comment]
Si tu peux faire le PR en passant sur le json, oui je suis preneur.

**Comment by jim005** [comment]
j'ai poussé un nouveau PR qui change la récupération des flux en JSON. Si tu l’intègres alors je t'en proposerai d'autres ;-)

**Comment by lunarok** [comment]
C'est valider, je le teste chez moi dans la journée et après ça sera dans la prochaine stable au market. Merci
